// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hello(arg1) {
  return window['go']['api']['HelloApi']['Hello'](arg1);
}
